version: '3.8'

services:
  app:
    build: ./app
    env_file:
      - ./app/.env
    volumes:
      - ./app/src:/app/src
    depends_on:
      - database
      - rabbitmq
    networks:
      - backend

  web-proxy:
    build: ./web-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: on-failure
    networks:
      - backend

  database:
    image: postgres:16-alpine
    env_file:
      - ./database.env     
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend
    healthcheck:   #тест
      test: ["CMD-SHELL", "pg_isready -U user -d mldb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_data:
  postgres_data:

networks:
  backend:
    driver: bridge